#common var used in the project
field = ['ehfpiAcc', 'geneSymbol', 'geneDescription', 'previousName', 'synonyms', 'entrezId',
                     'uniprotId', 'proteinName', 'ensemblGeneId', 'targetOrganism', 'drosophilaGene','humanHomolog', 'go',
                     'pathway', 'isVTP', 'resources', 'geneNote', 'fullName', 'abbreviation', 'aliases', 'strain',
                     'species', 'genus', 'family', 'group', 'kingdom', 'title', 'author', 'pubmedId', 'year', 'journal',
                     'abstract', 'doi', 'scope', 'assayType', 'reagent', 'phenotype', 'bioModelDescription',
                     'confirmatoryScreenDescription', 'primaryScreenDescription', 'hitsNumber', 'confirmedHitsNumber',
                     'primaryHitsNumber', 'screenNote']

fieldDes = ['EHFPI Accession', 'Gene Symbol', 'Gene Description', 'Previous Name', 'Gene Synonyms',
                        'Entrez Gene ID', 'UniProt ID', 'Protein Name', 'Ensembl Gene ID',
                        'Target Organism', 'Drosophila Gene','Human Homolog', 'GO', 'Pathway', 'isVTP', 'Resources', 'Gene Note',
                        'Pathogen Full Name', 'Pathogen Abbreviation', 'Pathogen Aliases', 'Pathogen(Strain)',
                        'Pathogen(Species)', 'Pathogen(Genus)', 'Pathogen(Family)', 'Pathogen(Group)', 'Pathogen(Kingdom)',
                        'Title', 'Author', 'Pubmed ID', 'Year', 'Journal', 'abstract', 'doi', 'Scope', 'Assay Type ',
                        'Reagent', 'Phenotype', 'BioModel Description', 'confirmatory Screen Description',
                        'primary Screen Description', 'Hits Number', 'ConfirmedHits Number', 'PrimaryHits Number',
                        'Screen Note']

fieldDic = {'ehfpiAcc': 'EHFPI Accession',
                        'geneSymbol': 'Gene Symbol',
                        'geneDescription': 'Gene Description',
                        'previousName': 'Previous Name',
                        'synonyms': 'Gene Synonyms',
                        'entrezId': 'Entrez Gene ID',
                        'uniprotId': 'UniProt ID',
                        'proteinName': 'Protein Name',
                        'ensemblGeneId': 'Ensembl Gene ID',
                        'targetOrganism': 'Target Organism',
                        'drosophilaGene':'Drosophila Gene',
                        'humanHomolog': 'Human Homolog',
                        'go': 'GO',
                        'pathway': 'Pathway',
                        'isVTP': 'isVTP',
                        'resources': 'Resources',
                        'geneNote': 'Gene Note',
                        'fullName': 'Pathogen Full Name',
                        'abbreviation': 'Pathogen Abbreviation',
                        'aliases': 'Pathogen Aliases',
                        'strain': 'Pathogen(Strain)',
                        'species': 'Pathogen(Species)',
                        'genus': 'Pathogen(Genus)',
                        'family': 'Pathogen(Family)',
                        'group': 'Pathogen(Group)',
                        'kingdom': 'Pathogen(Kingdom)',
                        'title': 'Title',
                        'author': 'Author',
                        'pubmedId': 'Pubmed ID',
                        'year': 'Year',
                        'journal': 'Journal',
                        'abstract': 'abstract',
                        'doi': 'doi',
                        'scope': 'Scope',
                        'assayType': 'Assay Type ',
                        'reagent': 'Reagent',
                        'phenotype': 'Phenotype',
                        'bioModelDescription': 'BioModel Description',
                        'confirmatoryScreenDescription': 'confirmatory Screen Description',
                        'primaryScreenDescription': 'primary Screen Description',
                        'hitsNumber': 'Hits Number',
                        'confirmedHitsNumber': 'ConfirmedHits Number',
                        'primaryHitsNumber': 'PrimaryHits Number',
                        'screenNote': 'Screen Note'
        }